site:
  title: Platform Foundation Bootcamp - RHOAI 
  url: https://shebistar.github.io/litemaas-sla-enforcer-kueue/
  start_page: modules::01_welcome.adoc

ui:
  bundle:
    url: ./content/docs-ui/ui-bundle.zip
  supplemental_files: ./content/supplemental-ui

content:
  edit_url: 'https://shebistar.github.io/litemaas-sla-enforcer-kueue/edit/main/{path}'
  sources:
    - url: ./
      start_path: content
      
output:
  dir: ./content/www

runtime:
  cache_dir: ./content/.cache/antora
