#!/usr/bin/env bash
#

echo "Starting build process..."
echo "Removing old site..."
rm -rf ./content/www/*
echo "Building new site..."

podman run --rm --name showroom-builder --platform linux/amd64 \
  -v "./:/antora:z" \
  docker.io/antora/antora --stacktrace site.yml

echo "Build process complete. Check the ./www folder for the generated site."
echo "To view the site locally, run the following command: utilities/lab-serve"
echo "If already running then browse to http://localhost:8082/index.html"
